import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from './components/header/header'
import Footer from './components/footer/footer'
import ResponseAPIProvider from './(generator)/lib/contexts/ResponseAPIContext'
import AuthContextProvider from './(login)/lib/contexts/AuthContext'
import NotificationProvider from './(notifications)/lib/contexts/NotificationProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
      <body className={inter.className}>
        <NotificationProvider>
          <AuthContextProvider>
            <Header />
            <ResponseAPIProvider>
              <main className='m-10 min-h-[60.5vh]'>
                {children}
              </main>
            </ResponseAPIProvider>
            <Footer />
          </AuthContextProvider>
        </NotificationProvider>
      </body>
    </html>
  )
}
