import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from './components/header/header'
import Footer from './components/footer/footer'
import MessageContextProvider from './lib/contexts/MessageContext'
import AuthContextProvider from './lib/contexts/AuthContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
      <body className={inter.className}>
        <AuthContextProvider>
          <Header />
          <MessageContextProvider>
            <main className='m-10 min-h-[60.5vh]'>
              {children}
            </main>
          </MessageContextProvider>
          <Footer />
        </AuthContextProvider>
      </body>
    </html>
  )
}
