import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from './components/header/header'
import Footer from './components/footer/footer'
import ResponseAPIProvider from './(generator)/lib/contexts/ResponseAPIContext'
import AuthContextProvider from './(login)/lib/contexts/AuthContext'
import NotificationProvider from './(notifications)/lib/contexts/NotificationProvider'
import useTheme from './lib/theme/useTheme'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const { verifyTheme } = useTheme()
  
  const theme = verifyTheme()

  console.log(theme);

  return (
    <html lang="pt-br" className={theme}>
      <body className={`${inter.className}`} >
          <NotificationProvider>
            <AuthContextProvider>
              <Header />
              <ResponseAPIProvider>
                <main className='m-3 md:m-5 lg:m-10 xl:m-14 min-h-[60.5vh]'>
                  {children}
                </main>
              </ResponseAPIProvider>
              <Footer />
            </AuthContextProvider>
          </NotificationProvider>
      </body>
    </html>
  )
}
